config/routes.rb
Rails.application.routes.draw do



  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Facebook::Messenger::Server, at: 'bot'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  resources :user_page, only: [:create]
  resources :page_bots, only: [:show, :index] do
    resources :bot_events
  end
  resources :page_bot_configurations, only: [:show, :update, :destroy]

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true

  def to_s
    "#{street}, #{city}, #{state} #{zip}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bot_event.rb
class BotEvent < ApplicationRecord
  belongs_to :page_bot
  has_one :address, as: :addressable, dependent: :destroy
  has_one :time_window, as: :timeable, dependent: :destroy
  has_many :event_rsvps

  def self.params
    [:name, :description, :picture_url]
  end
end

app/models/event_rsvp.rb
class EventRsvp < ApplicationRecord
  belongs_to :bot_event
  belongs_to :sender
  
end

app/models/page_bot.rb
class PageBot < ApplicationRecord
  belongs_to :user
  has_many :bot_events

  def add_whitelisted_domain(domain)
    raise "Too many domains, there's a limit of 10." if whitelisted_domains.size >= 10
    thread_settings.add_domain(domain)
  end

  def remove_whitelisted_domain(domain)
    thread_settings.remove_domain(domain)
  end

  def whitelisted_domains
    thread_settings.domains || []
  end

  def thread_settings
    FacebookThreadSettings.new(self)
  end

  def graph
    @graph ||= Koala::Facebook::API.new(access_token) if access_token
  end

  def get_graph_picture
    update_attributes!(picture_url: graph.get_object("me?fields=picture")["picture"]["data"]["url"])
  end

  # Add subscribe functionality
  # Add whitelisted domain functionality for generic templates
  # Add menu + get started functionality
end

app/models/referrer.rb
class Referrer < ApplicationRecord
  belongs_to :referrer, class_name: 'Sender'
  belongs_to :referree, class_name: 'Sender'
  belongs_to :referrable, polymorphic: true
end

app/models/sender.rb
class Sender < ApplicationRecord
  FACEBOOK_PARAMS = %w(first_name
                       last_name
                       profile_pic
                       gender)
  validates :facebook_id, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_pic, presence: true
  validates :gender, presence: true

  has_many :event_rsvps

  def self.create_from_facebook!(facebook_id, facebook_params)
    self.create!(initialized_params(facebook_params).merge({facebook_id: facebook_id})) unless find_by(facebook_id: facebook_id)
  end

  def self.initialized_params(facebook_params)
    facebook_params.slice(*FACEBOOK_PARAMS).symbolize_keys
  end

  def update_from_facebook!(facebook_params)
    update_attributes!(facebook_params) if facebook_params != attributes.slice(*FACEBOOK_PARAMS)
  end
end

app/models/time_window.rb
class TimeWindow < ApplicationRecord
  belongs_to :timeable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :page_bots

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at) if auth.credentials.expires_at && auth.credentials.expires
      user.picture_url = auth.info.image
      user.save!
    end
  end

  def graph
    @graph ||= Koala::Facebook::API.new(oauth_token) if oauth_token
  end

  def pages
    graph.get_connections("me", "accounts").select {|page| !page["id"].to_i.in?(page_bots.pluck(:page_id)) }
  end

  def get_graph_picture
    update_attributes!(picture_url: graph.get_object("me?fields=picture")["picture"]["data"]["url"])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/bot_events_controller.rb
class BotEventsController < ApplicationController
  include PageBotable
  before_action :find_bot
  before_action :find_event, except: [:index, :create, :new]

  def show

  end

  def index
    @events = @bot.bot_events
  end

  def new
    @event = @bot.bot_events.new
  end

  def create
    service = BotEventCreationService.new(@bot, bot_event_params)
    begin
      service.create_event
      redirect_to page_bot_bot_event_path(@bot, service.event)
    rescue => e
      flash[:danger] = "#{e.message}"
      render :new
    end
  end

  def edit
  end

  def update
    service = BotEventUpdaterService.new(@bot, @event, bot_event_params)
    begin
      service.update_event
      redirect_to page_bot_bot_event_path(@bot, @event)
    rescue => e
      flash[:error] = "#{e.message}"
      render :edit
    end
  end

  def destroy
  end

  def bot_event_params
    params.require(:bot_event).permit(:name, :start_at, :end_at, :address_line, :picture_url, :description)
  end

  def find_event
    @event = BotEvent.find(params[:id])
  end
end

app/controllers/page_bot_configurations_controller.rb
class PageBotConfigurationsController < ApplicationController
  include PageBotable
  before_action :find_bot

  def show
  end

  def update
    @bot.add_whitelisted_domain(configuration_params[:domain])
    redirect_to page_bot_configuration_path(@bot)
  end

  def destroy
    @bot.remove_whitelisted_domain(configuration_params[:domain])
    redirect_to page_bot_configuration_path(@bot)
  end

  def configuration_params
    params.require(:configuration).permit(:domain)
  end
end

app/controllers/page_bots_controller.rb
class PageBotsController < ApplicationController
  include PageBotable
  before_action :find_bot, only: [:show]
  def show
  end

  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    puts request.env['omniauth.auth']
    user = User.from_omniauth(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/user_page_controller.rb
class UserPageController < ApplicationController
  def create
    page_service = ::PageAdditionService.new(page_params: page_params, user: current_user)
    if page_service.create_and_subscribe!
      redirect_to page_bot_path(page_service.bot)
    else
      flash[:danger] = "Something went wrong."
      redirect_to root_path
    end
  end

  def page_params
    params.require(:page).permit(:page_id, :name, :access_token, :perms)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(*controller)
   controller.include?(params[:controller])
  end

  def action?(*action)
   action.include?(params[:action])
  end

  def active?(controller)
    controller?(controller) ? 'active' : ''
  end

  def bootstrap_class_for flash_type
  { success: "alert-success", danger: "alert-danger", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/helpers/bot_events_helper.rb
module BotEventsHelper
  def address_form_helper
    @event.address ? @event.address.to_s : nil
  end

  def datetime_form_helper(column)
    @event.time_window ? @event.time_window.send(column).to_formatted_s(:long_ordinal) : nil
  end
end

app/helpers/bots_helper.rb
module BotsHelper
end

app/helpers/page_bot_configurations_helper.rb
module PageBotConfigurationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_page_helper.rb
module UserPageHelper
end

app/views/bot_events/_form.html.erb
<%= simple_form_for([@bot, @event]) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, placeholder: "GOTV canvass, beach cleanup, fundraising event" %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :start_at, as: :string, placeholder: 'November 4th at 9am', input_html: { value: datetime_form_helper(:start_at) } %>
    </div>
    <div class="col-md-6">
      <%= f.input :end_at, as: :string, placeholder: 'November 4th at 6pm', input_html: { value: datetime_form_helper(:end_at) } %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :address_line, as: :string, placeholder: '1600 Pennsylvania Avenue, Washington, DC', hint: 'No need to designate USA', required: false, input_html: { value: address_form_helper } %>
    </div>
    <div class="col-md-6">
      <%= f.input :picture_url, placeholder: "A link to a relavant picture", hint: 'Uploads coming soon.' %>
    </div>
  </div>

  <%= f.input :description, as: :text, placeholder: 'Come join us for our event. Remember to bring sunscreen, your friends and a stoked attitude.' %>

  <%= f.button :submit, @event.created_at ? 'Update event' : 'Create event', class: 'btn btn-success' %>
<% end %>

app/views/bot_events/edit.html.erb
<h3>Edit <%= @event.name %></h3>

<%= render 'form' %>

app/views/bot_events/index.html.erb
<h3>Events</h3>

<% if @events.any? %>
  <% @events.each do |event| %>
    <li><%= link_to event.name, page_bot_bot_event_path(@bot, event) %> <%= link_to 'Edit', edit_page_bot_bot_event_path(@bot, event) %></li>
  <% end %>
<% else %>
  <h3>You don't have any events yet.</h3>
<% end %>

<%= link_to 'New event', new_page_bot_bot_event_path(@bot), class: 'btn btn-lg btn-success'%>

app/views/bot_events/new.html.erb
<h3>Create an event</h3>

<%= render 'form' %>

app/views/bot_events/show.html.erb
<h3>Event: <%= @event.name %></h3>

<p>description: <%= @event.description %></p>
<p>address: <%= @event.address.to_s %></p>
<p>start_at: <%= @event.time_window.start_at.to_formatted_s(:long_ordinal) %></p>
<p>end_at: <%= @event.time_window.end_at.to_formatted_s(:long_ordinal) %></p>
<p>img: <%= image_tag @event.picture_url %></p>