config/routes.rb
Rails.application.routes.draw do



  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Facebook::Messenger::Server, at: 'bot'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  resources :user_page, only: [:create]
  resources :page_bots, only: [:show, :index] do
    resources :bot_events
  end
  resources :page_bot_configurations, only: [:show, :update, :destroy]

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true

  def to_s
    "#{street}, #{city}, #{state} #{zip}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bot_event.rb
class BotEvent < ApplicationRecord
  belongs_to :page_bot
  has_one :address, as: :addressable, dependent: :destroy
  has_one :time_window, as: :timeable, dependent: :destroy
  has_many :event_rsvps

  def self.params
    [:name, :description, :picture_url]
  end
end

app/models/event_rsvp.rb
class EventRsvp < ApplicationRecord
  belongs_to :bot_event
  belongs_to :sender
  
end

app/models/page_bot.rb
class PageBot < ApplicationRecord
  belongs_to :user
  has_many :bot_events

  def add_whitelisted_domain(domain)
    raise "Too many domains, there's a limit of 10." if whitelisted_domains.size >= 10
    thread_settings.add_domain(domain)
  end

  def remove_whitelisted_domain(domain)
    thread_settings.remove_domain(domain)
  end

  def whitelisted_domains
    thread_settings.domains || []
  end

  def thread_settings
    FacebookThreadSettings.new(self)
  end

  def graph
    @graph ||= Koala::Facebook::API.new(access_token) if access_token
  end

  def get_graph_picture
    update_attributes!(picture_url: graph.get_object("me?fields=picture")["picture"]["data"]["url"])
  end

  # Add subscribe functionality
  # Add whitelisted domain functionality for generic templates
  # Add menu + get started functionality
end

app/models/referrer.rb
class Referrer < ApplicationRecord
  belongs_to :referrer, class_name: 'Sender'
  belongs_to :referree, class_name: 'Sender'
  belongs_to :referrable, polymorphic: true
end

app/models/sender.rb
class Sender < ApplicationRecord
  FACEBOOK_PARAMS = %w(first_name
                       last_name
                       profile_pic
                       gender)
  validates :facebook_id, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_pic, presence: true
  validates :gender, presence: true

  has_many :event_rsvps

  def self.create_from_facebook!(facebook_id, facebook_params)
    self.create!(initialized_params(facebook_params).merge({facebook_id: facebook_id})) unless find_by(facebook_id: facebook_id)
  end

  def self.initialized_params(facebook_params)
    facebook_params.slice(*FACEBOOK_PARAMS).symbolize_keys
  end

  def update_from_facebook!(facebook_params)
    update_attributes!(facebook_params) if facebook_params != attributes.slice(*FACEBOOK_PARAMS)
  end
end

app/models/time_window.rb
class TimeWindow < ApplicationRecord
  belongs_to :timeable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :page_bots

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at) if auth.credentials.expires_at && auth.credentials.expires
      user.picture_url = auth.info.image
      user.save!
    end
  end

  def graph
    @graph ||= Koala::Facebook::API.new(oauth_token) if oauth_token
  end

  def pages
    graph.get_connections("me", "accounts").select {|page| !page["id"].to_i.in?(page_bots.pluck(:page_id)) }
  end

  def get_graph_picture
    update_attributes!(picture_url: graph.get_object("me?fields=picture")["picture"]["data"]["url"])
  end
end

app/controllers/bot_events_controller.rb
class BotEventsController < ApplicationController
  include PageBotable
  before_action :find_bot
  before_action :find_event, except: [:index, :create, :new]

  def show

  end

  def index
    @events = @bot.bot_events
  end

  def new
    @event = @bot.bot_events.new
  end

  def create
    service = BotEventCreationService.new(@bot, bot_event_params)
    begin
      service.create_event
      redirect_to page_bot_bot_event_path(@bot, service.event)
    rescue => e
      flash[:danger] = "#{e.message}"
      render :new
    end
  end

  def edit
  end

  def update
    service = BotEventUpdaterService.new(@bot, @event, bot_event_params)
    begin
      service.update_event
      redirect_to page_bot_bot_event_path(@bot, @event)
    rescue => e
      flash[:error] = "#{e.message}"
      render :edit
    end
  end

  def destroy
  end

  def bot_event_params
    params.require(:bot_event).permit(:name, :start_at, :end_at, :address_line, :picture_url, :description)
  end

  def find_event
    @event = BotEvent.find(params[:id])
  end
end

app/controllers/page_bots_controller.rb
class PageBotsController < ApplicationController
  include PageBotable
  before_action :find_bot, only: [:show]
  def show
  end

  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    puts request.env['omniauth.auth']
    user = User.from_omniauth(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/user_page_controller.rb
class UserPageController < ApplicationController
  def create
    page_service = ::PageAdditionService.new(page_params: page_params, user: current_user)
    if page_service.create_and_subscribe!
      redirect_to page_bot_path(page_service.bot)
    else
      flash[:danger] = "Something went wrong."
      redirect_to root_path
    end
  end

  def page_params
    params.require(:page).permit(:page_id, :name, :access_token, :perms)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(*controller)
   controller.include?(params[:controller])
  end

  def action?(*action)
   action.include?(params[:action])
  end

  def active?(controller)
    controller?(controller) ? 'active' : ''
  end

  def bootstrap_class_for flash_type
  { success: "alert-success", danger: "alert-danger", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/helpers/bot_events_helper.rb
module BotEventsHelper
  def address_form_helper
    @event.address ? @event.address.to_s : nil
  end

  def datetime_form_helper(column)
    @event.time_window ? @event.time_window.send(column).to_formatted_s(:long_ordinal) : nil
  end
end

app/helpers/bots_helper.rb
module BotsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_page_helper.rb
module UserPageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">


    <title>Atomiccampaign</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="navbar navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_url %>"><img src="/action_bot_logo.png" width="65" /></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="nav-pic" style="background-image: url(<%= current_user.picture_url %>)"></span>  <%= current_user.name %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Bots", page_bots_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Sign out", signout_path %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign in with Facebook", "/auth/facebook" %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container main-container">
      <%= flash_messages %>
      <% if controller?('page_bots', 'page_bot_configurations', 'bot_events') && !(controller?('page_bots') && action?('index')) %>
        <%= render 'page_bots/title', bot: @bot %>
        <%= render 'page_bots/side_nav' %>
        <div class="col-md-10">
            <%= render 'page_bots/sub_nav' if controller?('page_bots', 'bot_events') %>
            <%= yield %>
        </div>
      <% else %>
        <%= yield %>
      <% end %>
    </div><!-- /.container -->


    <div class="container" id="user-widget">
      <% if current_user %>
        Welcome <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", signout_path %>
      <% else %>
        <%= link_to "Sign in with Facebook", "/auth/facebook" %>
      <% end %>
    </div>
  </body>


</html>

app/views/pages/home.html.erb
<h1>Welcome to ActionBot!</h1>